INSERT INTO question (label, options, answer) VALUES
                                                   ("Quel roi a écrit la majorité des Psaumes dans la Bible ?", '["David", "Salomon", "Moïse", "Samuel"]', "David"),
                                                   ("Combien de livres y a-t-il dans l'Ancien Testament ?", '["39", "27", "66", "24"]', "39"),
                                                   ("Qui a été jeté dans la fosse aux lions ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le premier livre de la Bible ?", '["Genèse", "Exode", "Lévitique", "Nombres"]', "Genèse"),
                                                   ("Quel animal a été envoyé pour annoncer la fin du déluge ?", '["Colombe", "Corbeau", "Hirondelle", "Aigle"]', "Colombe"),
                                                   ("Combien de plaies ont frappé l'Égypte lors de l'Exode ?", '["10", "7", "5", "12"]', "10"),
                                                   ("Qui a construit l'arche de Noé ?", '["Noé", "Moïse", "Adam", "Abraham"]', "Noé"),
                                                   ("Combien de jours Jésus a-t-il passé dans le désert pour jeûner ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Quel est le dernier livre de la Bible ?", '["Apocalypse", "Réalité", "Résurrection", "Regard"]', "Apocalypse"),
                                                   ("Quelle est la mère de Jésus ?", '["Marie", "Élisabeth", "Anne", "Rachel"]', "Marie"),
                                                   ("Combien d'apôtres Jésus avait-il ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Qui a été vendu par ses frères comme esclave ?", '["Joseph", "Jacob", "Isaac", "Abraham"]', "Joseph"),
                                                   ("Combien de personnes Moïse a-t-il nourries avec du pain et du poisson ?", '["5000", "3000", "7000", "10000"]', "5000"),
                                                   ("Qui a été emmené au ciel sans goûter à la mort ?", '["Élie", "Énoch", "Moïse", "Noé"]', "Énoch"),
                                                   ("Quelle est la première lettre de Paul dans le Nouveau Testament ?", '["Romains", "Corinthiens", "Galates", "Éphésiens"]', "Romains"),
                                                   ("Quel est le dernier livre du Nouveau Testament ?", '["Apocalypse", "Réalité", "Résurrection", "Regard"]', "Apocalypse"),
                                                   ("Quel roi a construit le temple de Jérusalem ?", '["Salomon", "David", "Asa", "Josaphat"]', "Salomon"),
                                                   ("Combien de fils Jacob a-t-il eu ?", '["12", "7", "10", "5"]', "12"),
                                                   ("Qui était le père de Jean le Baptiste ?", '["Zacharie", "Élie", "Élisée", "Isaïe"]', "Zacharie"),
                                                   ("Où Jésus est-il né ?", '["Bethléem", "Nazareth", "Jérusalem", "Galilée"]', "Bethléem"),
                                                   ("Combien de disciples ont pêché toute la nuit sans rien attraper, jusqu'à ce que Jésus leur dise d'essayer encore ?", '["7", "12", "5", "3"]', "7"),
                                                   ("Quel roi a libéré les Israélites de l'esclavage en Égypte ?", '["Mojse", "David", "Salomon", "Pharaon"]', "Mojse"),
                                                   ("Quel animal a parlé à Balaam ?", '["Âne", "Cheval", "Chameau", "Mouton"]', "Âne"),
                                                   ("Quel disciple a trahi Jésus pour 30 pièces d'argent ?", '["Judas", "Pierre", "Jean", "André"]', "Judas"),
                                                   ("Quelle mer Moïse a-t-il ouvert pour permettre aux Israélites de traverser ?", '["Mer Rouge", "Mer Méditerranée", "Mer Morte", "Mer de Galilée"]', "Mer Rouge"),
                                                   ("Quelle est la dernière parole de Jésus sur la croix ?", '["Tout est accompli", "Pardonne-leur", "Père, entre tes mains je remets mon esprit", "Eli, Eli, lama sabachthani"]', "Père, entre tes mains je remets mon esprit"),
                                                   ("Quel animal est mentionné dans la parabole du bon Samaritain ?", '["Âne", "Mouton", "Chien", "Cheval"]', "Âne"),
                                                   ("Combien de jours a duré le déluge selon la Bible ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Qui a construit la tour de Babel ?", '["Les humains", "Dieu", "Nimrod", "Caïn"]', "Les humains"),
                                                   ("Combien de disciples Jésus a-t-il choisi ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Quel est le nom de l'archange qui est souvent mentionné dans la Bible ?", '["Michel", "Gabriel", "Raphaël", "Uriel"]', "Michel"),
                                                   ("Qui était le plus jeune fils de Jacob ?", '["Benjamin", "Joseph", "Ruben", "Siméon"]', "Benjamin"),
                                                   ("Quelle est la première lettre de Pierre dans le Nouveau Testament ?", '["1 Pierre", "2 Pierre", "1 Corinthiens", "1 Thessaloniciens"]', "1 Pierre"),
                                                   ("Quel roi a vu une main écrire sur le mur lors d'un festin ?", '["Belschatsar", "Nabucodonosor", "Darius", "Artaxerxès"]', "Belschatsar"),
                                                   ("Qui a été englouti par un grand poisson ?", '["Jonas", "Moïse", "David", "Samuel"]', "Jonas"),
                                                   ("Quelle est la première épître de Jean dans le Nouveau Testament ?", '["1 Jean", "2 Jean", "3 Jean", "Jude"]', "1 Jean"),
                                                   ("Qui a été jeté dans la fosse aux lions mais en est sorti indemne ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quelle est la mère de Jésus ?", '["Marie", "Élisabeth", "Anne", "Rachel"]', "Marie"),
                                                   ("Quel est le premier livre de la Bible ?", '["Genèse", "Exode", "Lévitique", "Nombres"]', "Genèse"),
                                                   ("Quel animal a été envoyé pour annoncer la fin du déluge ?", '["Colombe", "Corbeau", "Hirondelle", "Aigle"]', "Colombe"),
                                                   ("Combien de plaies ont frappé l'Égypte lors de l'Exode ?", '["10", "7", "5", "12"]', "10"),
                                                   ("Combien de personnes Moïse a-t-il nourries avec du pain et du poisson ?", '["5000", "3000", "7000", "10000"]', "5000"),
                                                   ("Quel est le dernier livre de la Bible ?", '["Apocalypse", "Réalité", "Résurrection", "Regard"]', "Apocalypse"),
                                                   ("Quel roi a construit le temple de Jérusalem ?", '["Salomon", "David", "Asa", "Josaphat"]', "Salomon"),
                                                   ("Combien de fils Jacob a-t-il eu ?", '["12", "7", "10", "5"]', "12"),
                                                   ("Qui était le père de Jean le Baptiste ?", '["Zacharie", "Élie", "Élisée", "Isaïe"]', "Zacharie"),
                                                   ("Où Jésus est-il né ?", '["Bethléem", "Nazareth", "Jérusalem", "Galilée"]', "Bethléem"),
                                                   ("Combien de disciples ont pêché toute la nuit sans rien attraper, jusqu'à ce que Jésus leur dise d'essayer encore ?", '["7", "12", "5", "3"]', "7"),
                                                   ("Quel roi a libéré les Israélites de l'esclavage en Égypte ?", '["Mojse", "David", "Salomon", "Pharaon"]', "Mojse"),
                                                   ("Quel animal a parlé à Balaam ?", '["Âne", "Cheval", "Chameau", "Mouton"]', "Âne"),
                                                   ("Quel disciple a trahi Jésus pour 30 pièces d'argent ?", '["Judas", "Pierre", "Jean", "André"]', "Judas"),
                                                   ("Quelle mer Moïse a-t-il ouvert pour permettre aux Israélites de traverser ?", '["Mer Rouge", "Mer Méditerranée", "Mer Morte", "Mer de Galilée"]', "Mer Rouge"),
                                                   ("Quelle est la dernière parole de Jésus sur la croix ?", '["Tout est accompli", "Pardonne-leur", "Père, entre tes mains je remets mon esprit", "Eli, Eli, lama sabachthani"]', "Père, entre tes mains je remets mon esprit"),
                                                   ("Quel animal est mentionné dans la parabole du bon Samaritain ?", '["Âne", "Mouton", "Chien", "Cheval"]', "Âne"),
                                                   ("Combien de jours a duré le déluge selon la Bible ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Qui a construit la tour de Babel ?", '["Les humains", "Dieu", "Nimrod", "Caïn"]', "Les humains"),
                                                   ("Combien de disciples Jésus a-t-il choisi ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Quel est le nom de l'archange qui est souvent mentionné dans la Bible ?", '["Michel", "Gabriel", "Raphaël", "Uriel"]', "Michel"),
                                                   ("Qui était le plus jeune fils de Jacob ?", '["Benjamin", "Joseph", "Ruben", "Siméon"]', "Benjamin"),
                                                   ("Quelle est la première lettre de Pierre dans le Nouveau Testament ?", '["1 Pierre", "2 Pierre", "1 Corinthiens", "1 Thessaloniciens"]', "1 Pierre"),
                                                   ("Quel roi a vu une main écrire sur le mur lors d'un festin ?", '["Belschatsar", "Nabucodonosor", "Darius", "Artaxerxès"]', "Belschatsar"),
                                                   ("Qui a été englouti par un grand poisson ?", '["Jonas", "Moïse", "David", "Samuel"]', "Jonas"),
                                                   ("Quelle est la première épître de Jean dans le Nouveau Testament ?", '["1 Jean", "2 Jean", "3 Jean", "Jude"]', "1 Jean"),
                                                   ("Quel est le nom de l'épouse d'Adam dans la Bible ?", '["Ève", "Sara", "Rebecca", "Rachel"]', "Ève"),
                                                   ("Combien de frères Joseph avait-il ?", '["11", "5", "8", "10"]', "11"),
                                                   ("Qui a marché sur l'eau avec Jésus ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le mont où Moïse a reçu les 10 commandements ?", '["Sinaï", "Carmel", "Tabor", "Horeb"]', "Sinaï"),
                                                   ("Qui a été jeté dans la fosse aux lions mais n'a pas été dévoré ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le nom du jardin où Adam et Ève ont vécu avant la chute ?", '["Eden", "Sion", "Jéricho", "Gethsémani"]', "Eden"),
                                                   ("Qui a construit l'arche de l'alliance dans l'Ancien Testament ?", '["Betsaleel", "Noé", "Moïse", "Aaron"]', "Betsaleel"),
                                                   ("Quelle est la dernière parole de Jésus sur la croix ?", '["Tout est accompli", "Pardonne-leur", "Père, entre tes mains je remets mon esprit", "Eli, Eli, lama sabachthani"]', "Père, entre tes mains je remets mon esprit"),
                                                   ("Quel animal est mentionné dans la parabole du bon Samaritain ?", '["Âne", "Mouton", "Chien", "Cheval"]', "Âne"),
                                                   ("Combien de jours a duré le déluge selon la Bible ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Qui a construit la tour de Babel ?", '["Les humains", "Dieu", "Nimrod", "Caïn"]', "Les humains"),
                                                   ("Combien de disciples Jésus a-t-il choisi ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Quel est le nom de l'archange qui est souvent mentionné dans la Bible ?", '["Michel", "Gabriel", "Raphaël", "Uriel"]', "Michel"),
                                                   ("Qui était le plus jeune fils de Jacob ?", '["Benjamin", "Joseph", "Ruben", "Siméon"]', "Benjamin"),
                                                   ("Quelle est la première lettre de Pierre dans le Nouveau Testament ?", '["1 Pierre", "2 Pierre", "1 Corinthiens", "1 Thessaloniciens"]', "1 Pierre"),
                                                   ("Quel roi a vu une main écrire sur le mur lors d'un festin ?", '["Belschatsar", "Nabucodonosor", "Darius", "Artaxerxès"]', "Belschatsar"),
                                                   ("Qui a été englouti par un grand poisson ?", '["Jonas", "Moïse", "David", "Samuel"]', "Jonas"),
                                                   ("Quelle est la première épître de Jean dans le Nouveau Testament ?", '["1 Jean", "2 Jean", "3 Jean", "Jude"]', "1 Jean"),
                                                   ("Quel est le nom de l'épouse d'Adam dans la Bible ?", '["Ève", "Sara", "Rebecca", "Rachel"]', "Ève"),
                                                   ("Combien de frères Joseph avait-il ?", '["11", "5", "8", "10"]', "11"),
                                                   ("Qui a marché sur l'eau avec Jésus ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le mont où Moïse a reçu les 10 commandements ?", '["Sinaï", "Carmel", "Tabor", "Horeb"]', "Sinaï"),
                                                   ("Qui a été jeté dans la fosse aux lions mais n'a pas été dévoré ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le nom du jardin où Adam et Ève ont vécu avant la chute ?", '["Eden", "Sion", "Jéricho", "Gethsémani"]', "Eden"),
                                                   ("Qui a construit l'arche de l'alliance dans l'Ancien Testament ?", '["Betsaleel", "Noé", "Moïse", "Aaron"]', "Betsaleel"),
                                                   ("Quelle est la dernière parole de Jésus sur la croix ?", '["Tout est accompli", "Pardonne-leur", "Père, entre tes mains je remets mon esprit", "Eli, Eli, lama sabachthani"]', "Père, entre tes mains je remets mon esprit"),
                                                   ("Quel animal est mentionné dans la parabole du bon Samaritain ?", '["Âne", "Mouton", "Chien", "Cheval"]', "Âne"),
                                                   ("Combien de jours a duré le déluge selon la Bible ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Qui a construit la tour de Babel ?", '["Les humains", "Dieu", "Nimrod", "Caïn"]', "Les humains"),
                                                   ("Combien de disciples Jésus a-t-il choisi ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Quel est le nom de l'archange qui est souvent mentionné dans la Bible ?", '["Michel", "Gabriel", "Raphaël", "Uriel"]', "Michel"),
                                                   ("Qui était le plus jeune fils de Jacob ?", '["Benjamin", "Joseph", "Ruben", "Siméon"]', "Benjamin"),
                                                   ("Quelle est la première lettre de Pierre dans le Nouveau Testament ?", '["1 Pierre", "2 Pierre", "1 Corinthiens", "1 Thessaloniciens"]', "1 Pierre"),
                                                   ("Quel roi a vu une main écrire sur le mur lors d'un festin ?", '["Belschatsar", "Nabucodonosor", "Darius", "Artaxerxès"]', "Belschatsar"),
                                                   ("Qui a été englouti par un grand poisson ?", '["Jonas", "Moïse", "David", "Samuel"]', "Jonas"),
                                                   ("Quelle est la première épître de Jean dans le Nouveau Testament ?", '["1 Jean", "2 Jean", "3 Jean", "Jude"]', "1 Jean"),
                                                   ("Quel est le nom de l'épouse d'Adam dans la Bible ?", '["Ève", "Sara", "Rebecca", "Rachel"]', "Ève"),
                                                   ("Combien de frères Joseph avait-il ?", '["11", "5", "8", "10"]', "11"),
                                                   ("Qui a marché sur l'eau avec Jésus ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le mont où Moïse a reçu les 10 commandements ?", '["Sinaï", "Carmel", "Tabor", "Horeb"]', "Sinaï"),
                                                   ("Qui a été jeté dans la fosse aux lions mais n'a pas été dévoré ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quel est le nom du jardin où Adam et Ève ont vécu avant la chute ?", '["Eden", "Sion", "Jéricho", "Gethsémani"]', "Eden"),
                                                   ("Qui a construit l'arche de l'alliance dans l'Ancien Testament ?", '["Betsaleel", "Noé", "Moïse", "Aaron"]', "Betsaleel"),
                                                   ("Quel prophète a été enlevé au ciel dans un char de feu ?", '["Élie", "Élisée", "Jérémie", "Ézéchiel"]', "Élie"),
                                                   ("Quel roi a écrit les Psaumes ?", '["David", "Salomon", "Saül", "Asa"]', "David"),
                                                   ("Qui a été jeté dans la fosse aux lions mais en est sorti indemne ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel apôtre a renié Jésus trois fois avant le chant du coq ?", '["Pierre", "Jean", "André", "Jacques"]', "Pierre"),
                                                   ("Quelle est la mère de Jésus ?", '["Marie", "Élisabeth", "Anne", "Rachel"]', "Marie"),
                                                   ("Quel est le premier livre de la Bible ?", '["Genèse", "Exode", "Lévitique", "Nombres"]', "Genèse"),
                                                   ("Quel animal a été envoyé pour annoncer la fin du déluge ?", '["Colombe", "Corbeau", "Hirondelle", "Aigle"]', "Colombe"),
                                                   ("Combien de plaies ont frappé l'Égypte lors de l'Exode ?", '["10", "7", "5", "12"]', "10"),
                                                   ("Combien de personnes Moïse a-t-il nourries avec du pain et du poisson ?", '["5000", "3000", "7000", "10000"]', "5000"),
                                                   ("Quel est le dernier livre de la Bible ?", '["Apocalypse", "Réalité", "Résurrection", "Regard"]', "Apocalypse"),
                                                   ("Quel roi a construit le temple de Jérusalem ?", '["Salomon", "David", "Asa", "Josaphat"]', "Salomon"),
                                                   ("Combien de fils Jacob a-t-il eu ?", '["12", "7", "10", "5"]', "12"),
                                                   ("Qui était le père de Jean le Baptiste ?", '["Zacharie", "Élie", "Élisée", "Isaïe"]', "Zacharie"),
                                                   ("Où Jésus est-il né ?", '["Bethléem", "Nazareth", "Jérusalem", "Galilée"]', "Bethléem"),
                                                   ("Combien de disciples ont pêché toute la nuit sans rien attraper, jusqu'à ce que Jésus leur dise d'essayer encore ?", '["7", "12", "5", "3"]', "7"),
                                                   ("Quel roi a libéré les Israélites de l'esclavage en Égypte ?", '["Mojse", "David", "Salomon", "Pharaon"]', "Mojse"),
                                                   ("Quel animal a parlé à Balaam ?", '["Âne", "Cheval", "Chameau", "Mouton"]', "Âne"),
                                                   ("Quel disciple a trahi Jésus pour 30 pièces d'argent ?", '["Judas", "Pierre", "Jean", "André"]', "Judas"),
                                                   ("Quelle mer Moïse a-t-il divisée en deux pour permettre aux Israélites de traverser ?", '["Mer Rouge", "Mer Morte", "Mer Méditerranée", "Mer Galilée"]', "Mer Rouge"),
                                                   ("Qui a été appelé par Dieu alors qu'il était berger et est devenu roi d'Israël ?", '["David", "Moïse", "Salomon", "Josué"]', "David"),
                                                   ("Qui a tué le géant Goliath avec une fronde et une pierre ?", '["David", "Moïse", "Salomon", "Josué"]', "David"),
                                                   ("Quel est le plus court verset de la Bible ?", '["Jésus pleura", "Jésus marcha", "Jésus dit", "Jésus guérit"]', "Jésus pleura"),
                                                   ("Qui a écrit la plupart des lettres du Nouveau Testament ?", '["Paul", "Pierre", "Jean", "Jacques"]', "Paul"),
                                                   ("Combien de plaies ont frappé l'Égypte lors de l'Exode ?", '["10", "7", "5", "12"]', "10"),
                                                   ("Quel est le dernier livre de la Bible ?", '["Apocalypse", "Réalité", "Résurrection", "Regard"]', "Apocalypse"),
                                                   ("Quel roi a construit le temple de Jérusalem ?", '["Salomon", "David", "Asa", "Josaphat"]', "Salomon"),
                                                   ("Combien de fils Jacob a-t-il eu ?", '["12", "7", "10", "5"]', "12"),
                                                   ("Qui était le père de Jean le Baptiste ?", '["Zacharie", "Élie", "Élisée", "Isaïe"]', "Zacharie"),
                                                   ("Où Jésus est-il né ?", '["Bethléem", "Nazareth", "Jérusalem", "Galilée"]', "Bethléem"),
                                                   ("Combien de disciples ont pêché toute la nuit sans rien attraper, jusqu'à ce que Jésus leur dise d'essayer encore ?", '["7", "12", "5", "3"]', "7"),
                                                   ("Quel roi a libéré les Israélites de l'esclavage en Égypte ?", '["Moïse", "David", "Salomon", "Pharaon"]', "Moïse"),
                                                   ("Quel animal a parlé à Balaam ?", '["Âne", "Cheval", "Chameau", "Mouton"]', "Âne"),
                                                   ("Quel disciple a trahi Jésus pour 30 pièces d'argent ?", '["Judas", "Pierre", "Jean", "André"]', "Judas"),
                                                   ("Quelle mer Moïse a-t-il divisée en deux pour permettre aux Israélites de traverser ?", '["Mer Rouge", "Mer Morte", "Mer Méditerranée", "Mer Galilée"]', "Mer Rouge"),
                                                   ("Qui a été appelé par Dieu alors qu'il était berger et est devenu roi d'Israël ?", '["David", "Moïse", "Salomon", "Josué"]', "David"),
                                                   ("Qui a tué le géant Goliath avec une fronde et une pierre ?", '["David", "Moïse", "Salomon", "Josué"]', "David"),
                                                   ("Quel est le plus court verset de la Bible ?", '["Jésus pleura", "Jésus marcha", "Jésus dit", "Jésus guérit"]', "Jésus pleura"),
                                                   ("Qui a écrit la plupart des lettres du Nouveau Testament ?", '["Paul", "Pierre", "Jean", "Jacques"]', "Paul"),
                                                   ("Qui a été jeté dans la fosse aux lions mais en est sorti indemne ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Quel roi a eu une vision d'un grand arbre qui a été coupé ?", '["Nabucodonosor", "Belschatsar", "Darius", "Cyrus"]', "Nabucodonosor"),
                                                   ("Quel est le fruit de l'Esprit mentionné dans l'épître aux Galates ?", '["Amour", "Joie", "Paix", "Patience"]', "Amour"),
                                                   ("Qui a été jeté dans la fournaise ardente mais n'a pas été brûlé ?", '["Shadrach, Méshach et Abed-Nego", "Daniel", "Moïse", "Élie"]', "Shadrach, Méshach et Abed-Nego"),
                                                   ("Quelle est la première épître de Paul aux Corinthiens dans le Nouveau Testament ?", '["1 Corinthiens", "2 Corinthiens", "1 Thessaloniciens", "1 Pierre"]', "1 Corinthiens"),
                                                   ("Qui a écrit les Psaumes ?", '["David", "Salomon", "Asaph", "Moïse"]', "David"),
                                                   ("Quel roi a demandé à Dieu de lui accorder la sagesse ?", '["Salomon", "David", "Asa", "Josaphat"]', "Salomon"),
                                                   ("Qui a prié Dieu dans la fosse aux lions et a été sauvé ?", '["Daniel", "Jonas", "Noé", "Abraham"]', "Daniel"),
                                                   ("Combien de frères Joseph avait-il ?", '["11", "5", "8", "10"]', "11"),
                                                   ("Quelle est la dernière parole de Jésus sur la croix ?", '["Tout est accompli", "Pardonne-leur", "Père, entre tes mains je remets mon esprit", "Eli, Eli, lama sabachthani"]', "Père, entre tes mains je remets mon esprit"),
                                                   ("Quel animal est mentionné dans la parabole du bon Samaritain ?", '["Âne", "Mouton", "Chien", "Cheval"]', "Âne"),
                                                   ("Combien de jours a duré le déluge selon la Bible ?", '["40", "7", "30", "10"]', "40"),
                                                   ("Qui a construit la tour de Babel ?", '["Les humains", "Dieu", "Nimrod", "Caïn"]', "Les humains"),
                                                   ("Combien de disciples Jésus a-t-il choisi ?", '["12", "10", "7", "5"]', "12"),
                                                   ("Quel est le nom de l'archange qui est souvent mentionné dans la Bible ?", '["Michel", "Gabriel", "Raphaël", "Uriel"]', "Michel"),
                                                   ("Qui était le plus jeune fils de Jacob ?", '["Benjamin", "Joseph", "Ruben", "Siméon"]', "Benjamin"),
                                                   ("Quelle est la première lettre de Pierre dans le Nouveau Testament ?", '["1 Pierre", "2 Pierre", "1 Corinthiens", "1 Thessaloniciens"]', "1 Pierre")